name: explore
description: "Explore Github Action Composite"
inputs:
  nice-input:
    required: true
    description: "Testing passing input to composite"

runs:
  using: "composite"
  steps:
    - name: Display Nice Input
      run: echo "Nice Input = ${{ inputs.nice-input }}"
      shell: bash