name: explore
description: "Explore Github Action Composite"
inputs:
  nice-input:
    required: true
    description: "Testing passing input to composite"
  shared-env:
    required: true
    description: "Testing global environment variables for all jobs"

runs:
  using: "composite"
  steps:
    - name: Display Nice Input
      run: echo "Nice Input = ${{ inputs.nice-input }}"
    - name: Display Shared Environment Vairable
      run: echo "Shared Environment Variable = ${{ inputs.shared-env}}"