name: GitHub Actions Demo
on: push
jobs:
  caller_a:
    name: "Caller A"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Call Explore Composite"
        uses: ./.github/actions/explore
        with:
          nice-input: "I'm A"
  caller_b:
    name: "Caller B"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Call Explore Composite"
        uses: ./.github/actions/explore
        with:
          nice-input: "I'm B"
  finish_me:
    name: "Finish Me"
    runs-on: ubuntu-latest
    needs: [caller_a, caller_b]
    if: "contains(github.event.head_commit.message, 'deploy-production')"
    steps:
      - uses: actions/checkout@v2
      - name: "Optional Step"
        run: echo "Bye, Bye "